# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            S4H.ME
tagline:          'A Blog For Hikari Vanish'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://www.s4h.me
baseurl:          /

author:
  name:           'Hikari Vanish'
  url:            https://www.s4h.me

paginate:         5

# Custom vars

github:           https://github.com/hikarivanish
