# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            S4H.ME
tagline:          'A Blog For Hikari Vanish'
description:      'A Blog For Hikari,   Nothing Else.'
url:              http://www.s4h.me
baseurl:          /

author:
  name:           'Hikari Vanish'
  url:            https://www.s4h.me

paginate:         5

# Custom vars

github:           https://github.com/hikarivanish
